### PR TITLE
Exposes extensions payload in client

### PR DESCRIPTION
**Pull request by MasseGuillaume**

### CODE REVIEW

**Comment by ghostdogpr** [comment]
Hmm.. this is strange, the webhook calling CircleCI returns an error 400. I wonder if you're just super unlucky (never happened before except your previous PR) or if there is something broken 🤔

**Comment by ghostdogpr** [comment]
I checked the logs and this error only happens with your account. Maybe try relogging to github? 🤔

**Comment by MasseGuillaume** [comment]
Yup, re-login into circleci worked

**Comment by ghostdogpr** [comment]
> Yup, re-login into circleci worked

Phew, I was afraid any new PR would have this problem 😅

**Pull request merged**
