### PR TITLE
the Parser migration from fastparse to cats-parse

### PR DESCRIPTION
**Pull request by lvitaly**
Relates to #631

### CODE REVIEW

**Comment by YulawOne** [comment]
I think it worth to make some performance comparison between fastparse and cats-parse solution

**Comment by timzaak** [comment]
If it's going on?

**Comment by ghostdogpr** [comment]
@timzaak I don't think there was much progress, in case you're interested to contribute ;)

**Comment by timzaak** [comment]
I tried, but cats-parse api is now very different from fastparse. Almostly need rewrite all the code. and need wait this issue: https://github.com/typelevel/cats-parse/issues/186
I will try to pass the `Parser` test cases. https://github.com/timzaak/caliban/tree/cat-parse

Honestly, It's may be a good idea to wait fastparse support Scala 3.

**Comment by lvitaly** [comment]
@timzaak @ghostdogpr I rewrote Parser with cats-parse but stuck with whitespace implementation. I will commit the last changes soon.

**Comment by timzaak** [comment]
cats-parse 0.3.1 has changed a lot comparing with 0.1 
you may update it firstly

**Comment by timzaak** [comment]
@lvitaly I changed a lot depends on your work.

**Comment by timzaak** [comment]
https://github.com/timzaak/caliban/blob/cat-parse/core/src/main/scala/caliban/parsing/Parser2.scala#L32 the whitespaces can work

**Comment by timzaak** [comment]
@lvitaly @ghostdogpr 
[Parser2.scala](https://github.com/timzaak/caliban/blob/cat-parse/core/src/main/scala/caliban/parsing/Parser2.scala) now can pass all the test cases( except invalid syntax, becase cats-parse error is different from fastparse)


The performance would improve by handle `whitespaces` and `trackback` more carefully.  

PS:
1. string value implementation is from cats-parse JsonString.
2. I firstly use cats-parse, so it needs code review.

**Comment by timzaak** [comment]
ref: https://github.com/typelevel/cats-parse/issues/188#issuecomment-808873555

**Comment by timzaak** [comment]
I rewrite it, and it looks good to me, I don't know if it is good to replace fastparse, or just provide an alternative choice for GraphQL parse.

**Comment by ghostdogpr** [comment]
@timzaak one thing that would be interesting is to run the caliban benchmark project with fastparse vs cats-parse. If there is not much difference maybe we could migrate entirely. If cats-parse is much slower maybe we only adopt it temporarily inside a "scala3" branch.

**Comment by ghostdogpr** [comment]
Closing in favor of https://github.com/ghostdogpr/caliban/pull/850

**Pull request closed without merging**
