### PR TITLE
Coerce non-null values into lists of size one

### PR DESCRIPTION
**Pull request by guymers**
As per the specification, if a value passed as an input to a list type is
not a list and is not null then it should be coerced into a list of size
one.

### CODE REVIEW

**Review by frekw — APPROVED** [review]
Looks great, thanks! 🙏

**Comment by guymers** [comment]
I can't get `listListInt: ListListIntArg => Option[List[Option[List[Option[Int]]]]]` to compile on Scala 3 so I have made the tests that need it only run on Scala 2.

**Comment by frekw** [comment]
@guymers what compilation error are you seeing on Scala 3? I saw that you replaced `genMacro` since it's not available for Scala 3, but can't see what failed for you after doing so :)

**Comment by ghostdogpr** [comment]
Maybe ran into this? https://github.com/lampepfl/dotty/issues/13044

**Comment by guymers** [comment]
Yeah its that. Defining a schema and arg builder for `Option[List[Option[Int]]]` allowed `listInt` to compile, but defining them doesn't help for `Option[List[Option[List[Option[Int]]]]]`.

**Comment by ghostdogpr** [comment]
Thanks for the fix and adding all the test cases!

**Pull request merged**
