### PR TITLE
Remove deprecated code

### PR DESCRIPTION
**Pull request by ghostdogpr**
Since the next version will be a major version, let's get rid of deprecated code.

I disabled Mima because it's too annoying to add all the rules and it's already decided we will break.

### CODE REVIEW

**Review by kyri-petrou — APPROVED** [review]

**Comment by paulpdaniels** [comment]
The `Rendering` code too?

**Comment by ghostdogpr** [comment]
Too soon?

**Comment by kyri-petrou** [comment]
I'm wondering whether we should aim to keep deprecated methods which are completely deleted for a few more major version just to give users enough time to migrate.

For legacy services I usually update non-CVE dependencies every 6 months or so, and it can be very annoying when methods completely disappear and I have to go looking where its replacement is - it makes a chore even more of a chore (not talking about Caliban ofc)

**Comment by ghostdogpr** [comment]
The reason I removed it is because I think no one uses those directly, they should be using `.render` instead. Apart from that I agree with you.

**Comment by ghostdogpr** [comment]
Restored Rendering

**Pull request merged**
