### PR TITLE
Do not render emplty field list

### PR DESCRIPTION
**Pull request by Fluxx**
According to [the GraphQL object spec](https://spec.graphql.org/June2018/#sec-Objects), for a given `type Foo` the fields definition for that type is optional. As far as I can tell, if you want to not specify a fields list, you need to also omit the wrapping `{...}`. i.e:

```graphql
// This is invalid
type Foo {
}

// This is valid
type Foo
```

Currently, Caliban always prints schema with the wrapping `{...}`, even if there are no fields for the type, which I believe is invalid. I tested this against our schema in Apollo and saw the below. Sensitive parts omitted, but the important part is the AST parse failure.

```
$ echo 'schema {query: Q} type Q {}' | rover subgraph check [...]
Checking the proposed schema for subgraph [...]
error: Could not parse partial schema as AST.

$ echo 'schema {query: Q} type Q' | rover subgraph check [...]
Checking the proposed schema for [...]
Compared 108 schema changes against 25 operations
```

### CODE REVIEW

**Comment by ghostdogpr** [comment]
Looks okay! The CI failed because of formatting, can you run `fmt` in sbt?

**Comment by Fluxx** [comment]
Will do.

Also, we ran into a similar problem where an empty `schema` also causes issues, where both `schema` and `schema {}` are invalid. I will see if I can make that change as part of this PR as well.

**Comment by Fluxx** [comment]
Ran `fmt` and also added some behavior to handle empty schemas. Please take a look!

**Review by ghostdogpr — APPROVED** [review]
Thanks!

**Pull request merged**
