### PR TITLE
Correctly validate optional list in inputs

### PR DESCRIPTION
**Pull request by darl**
Didn't read graphql spec, but this seems like correct behaviour.

### CODE REVIEW

**Comment by ghostdogpr** [comment]
Your fix is correct in the case of a List but I think we should go even further.

In the spec (http://spec.graphql.org/June2018/#sec-Scalars): `For all types below, with the exception of Non‐Null, if the explicit value null is provided, then the result of input coercion is null.`.  So I think other types need the same treatment. @frekw right?

**Review by frekw — APPROVED** [review]
The change itself looks good. But I think we should do the same for `INPUT_OBJECT` and `ENUM` as well?

**Comment by frekw** [comment]
Ah you beat me to it @ghostdogpr :)

**Comment by darl** [comment]
So case with `// handle item as the first item in the list` is incorrect?

**Comment by darl** [comment]
Nevermind. I got it. Will fix soon

**Review by ghostdogpr — APPROVED** [review]
Perfect, thanks!

**Pull request merged**
