### PR TITLE
Add derives Schema.SemiAuto in schema code generation

### LINKED ISSUE #1667: Add derives Schema.SemiAuto in schema code generation
The only tricky part is that it should only be there for Scala 3. If we can't detect it automatically, we could make this behavior enabled by a parameter.

### PR DESCRIPTION
**Pull request by nox213**
closes #1667

-Add `addDerives` flag to toggle this feature
-Change`scalafmt - use runner.dialect to use scala3` because `derive` keyword is only supported from scala3. And `schemaWriterSpec` run scalafmt before comparing results.

### CODE REVIEW

**Comment by ghostdogpr** [comment]
Hmm there are fmt errors because of the scala3 dialect 🤔

**Comment by ghostdogpr** [comment]
Instead of changing the project .scalafmt.conf, in `SchemaWriterSpec` you can pass a path to `Formatter.format` that points to another .scalafmt.conf file, that can be used for the test only.

**Comment by nox213** [comment]
I fixed the problem. Thank you for your review. @ghostdogpr

**Review by ghostdogpr — APPROVED** [review]
Great, thanks!

**Pull request merged**
