### PR TITLE
Update Scala 2 to 2.13.10

### PR DESCRIPTION
**Pull request by kyri-petrou**
Ticks one of the #1497 list

### CODE REVIEW

**Comment by kyri-petrou** [comment]
Not sure why the `scripted` tests for Scala 3 is failing. Is this just a matter of restarting the workflow?

**Comment by ghostdogpr** [comment]
I restarted it

**Comment by kyri-petrou** [comment]
> I restarted it

Thanks, seems that it passed now :)

**Comment by ghostdogpr** [comment]
Thanks!

**Pull request merged**
