### PR TITLE
chore: update zio-http

### PR DESCRIPTION
**Pull request by uryyyyyyy**
zio-http API is changed between RC17 -> RC18.

### CODE REVIEW

**Comment by uryyyyyyy** [comment]
sorry, we may need to wait for tapir's update https://github.com/softwaremill/tapir/pull/1686

**Comment by ghostdogpr** [comment]
Yep, needs tapir update first but tapir tests showed a bug in zio-http so we probably need another release of zio-http.

**Comment by guizmaii** [comment]
The update has been merged in Tapir :)

**Comment by uryyyyyyy** [comment]
thanks! I'll prepare for the new tapir version.

**Comment by uryyyyyyy** [comment]
waiting this fix.
https://github.com/softwaremill/tapir/pull/1781

**Comment by uryyyyyyy** [comment]
@ghostdogpr PR updated. Is it ok to use tapir v0.20.0-M7 ?

**Comment by ghostdogpr** [comment]
@uryyyyyyy I'd prefer to wait for the next official tapir release rather than depending on a milestone version. Thanks for your work and the bug fix in tapir!

**Comment by uryyyyyyy** [comment]
OK, then let's wait their release. It's OK to change my PR If I'll be busy.

Thanks for the great tool.

**Comment by guizmaii** [comment]
This takes forever 😭

I will very soon need the static file server feature released in the latest zio-http version, already updated in the `master` branch of Tapir 😭

**Comment by ghostdogpr** [comment]
> This takes forever 😭
> 
> I will very soon need the static file server feature released in the latest zio-http version, already updated in the `master` branch of Tapir 😭

Yeah, they just did a M10 a few days ago. You can try asking Adam, I did for 0.19 and he published it quite quickly after I asked.

**Comment by ghostdogpr** [comment]
Tapir 0.20.0 was just released ^^ With zio-http bumped to 1.0.0.0-RC25

**Comment by uryyyyyyy** [comment]
ok, will try migration today.

**Comment by ghostdogpr** [comment]
@uryyyyyyy Added a dependency to `tapir-sttp-client-ws-zio1` to fix the (last?) problem

**Comment by ghostdogpr** [comment]
It's green! Thanks @uryyyyyyy

**Pull request merged**
