### PR TITLE
Update Scala to 2.12.13, 2.13.5

### PR DESCRIPTION
**Pull request by isuzuki**

### CODE REVIEW

**Comment by ghostdogpr** [comment]
Thanks! Weirdly the CI did not trigger, can you try login to https://app.circleci.com/ to see if it solves the issue?

**Comment by isuzuki** [comment]
Sorry, I logged in CircleCI, CI had triggered.
Thanks!

**Comment by ghostdogpr** [comment]
There's an error related to the silencer plugin, I think it should be upgraded to 1.7.3.

https://circleci.com/api/v1.1/project/github/ghostdogpr/caliban/8515/output/103/0?file=true&allocation-id=603dd1c9edc5021b69ca3531-0-build%2F1C7B091F

**Review by ghostdogpr — APPROVED** [review]
All green, thanks!

**Comment by isuzuki** [comment]
Thanks for your reviews!

**Pull request merged**
