### PR TITLE
Add federation to release

### PR DESCRIPTION
**Pull request by paulpdaniels**
Missed this in my last PR but found it while testing locally. Forgot to add the federation module to the aggregate for publishing

### CODE REVIEW

**Comment by ghostdogpr** [comment]
Wow, I also missed it, good catch!

**Comment by ghostdogpr** [comment]
Scalafmt seems unhappy.

**Comment by ghostdogpr** [comment]
It's `FederationSpec`, not sure why it didn't complain before 🤔

**Comment by paulpdaniels** [comment]
Not sure why that happened, but I fixed the spec to make it happy.

**Pull request merged**
