### PR TITLE
Optionally disable tracing of pure fields in `ApolloTracing` wrapper

### PR DESCRIPTION
**Pull request by kyri-petrou**
We previously discussed on Discord that it might be good to expose this as an option where users might prefer performance over correctness

### CODE REVIEW

**Review by ghostdogpr — APPROVED** [review]

**Comment by ghostdogpr** [comment]
How about `ApolloFederatedTracing`?

**Comment by kyri-petrou** [comment]
> How about `ApolloFederatedTracing`?

I didn't want to touch that since I wasn't sure whether it would cause any weird behaviour when queried fields are not included in the traces. Having said that, the same can be said about `ApolloTracing`. I'll add it and add a warning about it in both places

**Comment by kyri-petrou** [comment]
@ghostdogpr done

**Comment by ghostdogpr** [comment]
@paulpdaniels by any chance do you know if missing fields cause problems on Apollo side?

**Comment by kyri-petrou** [comment]
@ghostdogpr what are your thoughts? Shall we merge this in?

I'm thinking that given that it's optional to disable the the wrapping of pure values, users can try it out and check whether it works with their setup so there isn't much harm done in adding this

**Comment by ghostdogpr** [comment]
Sounds good 👍

**Review by ghostdogpr — APPROVED** [review]

**Pull request merged**
