### PR TITLE
Upgrade Sttp to 3.1.0

### LINKED ISSUE #732: upgrade to sttp 3.0.0
sttp 3.0.0 has been released for a while now. https://github.com/softwaremill/sttp/releases/tag/v3.0.0

### PR DESCRIPTION
**Pull request by javimartinez**
Closes #732

### CODE REVIEW

**Review by ghostdogpr — APPROVED** [review]
Very good, thank you! Good to see that not much was broken =)

I merged a PR upgrading scalafmt which causes conflicts. Can you rebase to the latest master?

**Comment by javimartinez** [comment]
Done! @ghostdogpr

**Review by ghostdogpr — APPROVED** [review]
Thanks again!

**Comment by kubukoz** [comment]
Cool beans :D @ghostdogpr are you planning a release?

**Comment by ghostdogpr** [comment]
Yep! I'm quite busy at work so it may have to wait the weekend but I will definitely.

**Comment by kubukoz** [comment]
No prob :)

**Pull request merged**
