### PR TITLE
feat(client): provide a way to select interfaces fields

### LINKED ISSUE #237: Caliban client: better helper for interfaces
Currently for each field that returns an interface, we generate a function that takes an optional `SelectionBuilder` for each type that implements the interface. If we want to select fields from the interface (common to all types), we still need to provide a `SelectionBuilder` for each type.

We need something more user-friendly for that particular use case.

### PR DESCRIPTION
**Pull request by AlixBa**
Closes #237

### CODE REVIEW

**Comment by AlixBa** [comment]
@ghostdogpr is the 2nd commit close enough to what you had in mind for #237?

**Comment by ghostdogpr** [comment]
@AlixBa what I was thinking is a little different. Let's say that for each subtype you want to get the common fields from the interface, plus an extra field for one of the subtypes. To do that, you have to repeat the interface fields for each subtypes. So I was thinking about adding an extra parameter to the `option` function, that takes an optional `SelectionBuilder` of the interface. That way, for my example, you only need to pass this one and the `SelectionBuilder` for the subtype that needs an extra field. Does that make sense?

By the way I merged your other PR, so you can rebase to get rid of the conflicts.

**Comment by ghostdogpr** [comment]
Ah, what I suggested doesn't work 😆 
```scala
def parentOption[A](
  onParent: Option[SelectionBuilder[Parent, A] = None,
  onSubType1: Option[SelectionBuilder[SubType1, A]] = None,
  onSubType2: Option[SelectionBuilder[SubType2, A]] = None
)
```
There is no way to merge the 2 A from the interface and the subtype.

So I think what you did is good. In my example, we can combine `parentInterface` and `parentOption` with `~` to select the common fields and the subtype ones.

**Comment by AlixBa** [comment]
@ghostdogpr I've added one. Not sure it is the right place/what you were expecting though ^^

**Comment by ghostdogpr** [comment]
Yep, that's good! Thanks!

**Pull request merged**
