### PR TITLE
Validate names in validateSchema

### LINKED ISSUE #1729: GraphQL.render does not validate type and field names
For example, for a type defined like
```scala
@GQLName("Foo { str: String }\ntype Bar")
case class Foo(
    @GQLName("bool: Boolean\n  num")
    num: Int
)
```
the renderer simply emits
```graphql
type Foo { str: String }
type Bar {
  bool: Boolean
  num: Int!
}
```
without any concern.

Pretty much same effect can be achieved by naming classes and fields directly via backticks:
```scala
case class `Foo { str: String }\ntype Bar`(
  `bool: Boolean\n  num`: Int
)
```

### PR DESCRIPTION
**Pull request by ghostdogpr**
Closes #1729

### CODE REVIEW

**Comment by ghostdogpr** [comment]
@kyri-petrou any idea why Mima is complaining about private methods?

**Review by frekw — APPROVED** [review]
Nice!

**Comment by kyri-petrou** [comment]
> @kyri-petrou any idea why Mima is complaining about private methods?

My guess is that it's because they're `package` private, which means that users could have namespaced the file under `package caliban` to use them.

Another reason I guess might be in cases that a user is using `caliban-core` 2.2.2 and `caliban-<something>` at 2.2.1 pulled from different dependencies

Given that there are almost no other libraries that depend on caliban directly to create such mismatch, and that end-users namespacing code under `package caliban` are likely not publishing artifacts, I think we're safe to add these as ignored in mima.

**Comment by ghostdogpr** [comment]
Adding an exclusion for mima

**Pull request merged**
