### PR TITLE
validation: allow Ints passed to Float arguments

### PR DESCRIPTION
**Pull request by darl**
Maybe translation similar to #1136 would be better. 
But I don't know reasons behind #1136 implementation.

### CODE REVIEW

**Comment by ghostdogpr** [comment]
The reason behind the transformation of `StringValue` into `EnumValue` is so that when you use `Field` metadata, you get a value of a type that matches the schema. Basically it's coercing "early" so that you don't even need to do it in the ArgBuilder. I guess we should apply the same logic for this case. @frekw right? What do you think?

**Comment by ghostdogpr** [comment]
@darl I opened https://github.com/ghostdogpr/caliban/pull/1150

**Comment by frekw** [comment]
@ghostdogpr yeah I think doing it like in #1150 is the only way to do it since we're basically paving over limitations in JSON. If I read the spec correctly, coercion should only be applied when we're dealing with variables so doing it like this probably runs the risk of accepting invalid queries for `Content-Type: application/graphql`.

**Comment by ghostdogpr** [comment]
@frekw shouldn't it be applied to arguments too? http://spec.graphql.org/June2018/#sec-Coercing-Field-Arguments

**Comment by ghostdogpr** [comment]
Answering myself: not for enums, but for float yes. Will handle it in my other PR.

**Pull request closed without merging**
