### PR TITLE
ClientWriter. Generate View and SelectionBuilder

### PR DESCRIPTION
**Pull request by iRevive**
### Synopsis

The reason behind this change is to preserve the consistency between text schema and generated models.

When you add a new field to the schema, you can simply forget to propagate it to the models in tests. When the view is generated from the text schema, the chance to forget a new field is lower.

In the current implementation, a view class needs to be defined manually. And the full selection query must be constructed manually as well.

The generator has enough information to generate a view case class.

Generation of View classes disabled by default. It can be enabled via `ClientWriter.write(..., genView = true)`

### Example

Schema:
```scala
type Q {
  users: [User!]!
}
  
type Character {
  name: String!
  age: Int!
  nicknames(arg: Int): [String!]!
}

type User {
  characters(name: String!): [Character!]!
}
```

Output:
```scala
import caliban.client.FieldBuilder._
import caliban.client.SelectionBuilder._
import caliban.client._

object Client {

  type Q
  object Q {

    final case class QView[UsersSelection](users: List[UsersSelection])

    type ViewSelection[UsersSelection] = SelectionBuilder[Q, QView[UsersSelection]]

    def view[UsersSelection](usersSelection: SelectionBuilder[User, UsersSelection]): ViewSelection[UsersSelection] =
      users(usersSelection).map(users => QView(users))

    def users[A](innerSelection: SelectionBuilder[User, A]): SelectionBuilder[Q, List[A]] =
      Field("users", ListOf(Obj(innerSelection)))
  }

  type Character
  object Character {

    final case class CharacterView(name: String, age: Int, nicknames: List[String])

    type ViewSelection = SelectionBuilder[Character, CharacterView]

    def view(nicknamesArg: Option[Int] = None): ViewSelection = (name ~ age ~ nicknames(nicknamesArg)).map {
      case ((name, age), nicknames) => CharacterView(name, age, nicknames)
    }

    def name: SelectionBuilder[Character, String] = Field("name", Scalar())
    def age: SelectionBuilder[Character, Int]     = Field("age", Scalar())
    def nicknames(arg: Option[Int] = None): SelectionBuilder[Character, List[String]] =
      Field("nicknames", ListOf(Scalar()), arguments = List(Argument("arg", arg)))
  }

  type User
  object User {

    final case class UserView[CharactersSelection](characters: List[CharactersSelection])

    type ViewSelection[CharactersSelection] = SelectionBuilder[User, UserView[CharactersSelection]]

    def view[CharactersSelection](
        charactersName: String
     )(charactersSelection: SelectionBuilder[Character, CharactersSelection]): ViewSelection[CharactersSelection] =
      characters(charactersName)(charactersSelection).map(characters => UserView(characters))

    def characters[A](name: String)(innerSelection: SelectionBuilder[Character, A]): SelectionBuilder[User, List[A]] =
      Field("characters", ListOf(Obj(innerSelection)), arguments = List(Argument("name", name)))
  }

}
```

### CODE REVIEW

**Comment by paulpdaniels** [comment]
Thanks for the contribution!

 I have two main questions. 1) how does this handle recursive structures and 2) this seems to require all the fields all the time how will users get partial results?

**Comment by iRevive** [comment]
Hi @paulpdaniels. 

## Recursive schemas

I added a test for the recursive structure scenario. You can control the depth of a selection:

```scala
 // select first level
val selection1: SelectionBuilder[Character, CharacterView[(String, Int)]] = 
  Character.view("some filter")(Character.name ~ Character.age)

 // select first and second levels
val selection2: SelectionBuilder[Character, CharacterView[CharacterView[(String, Int)]]] = 
  Character.view("filter 1")(Character.view("filter 2")(Character.name ~ Character.age))
```

The schema:
```scala
type Character {
  name: String!
  age: Int!
  friends(filter: String): [Character!]!
}
```

The output is:
```scala
import caliban.client.FieldBuilder._
import caliban.client.SelectionBuilder._
import caliban.client._

object Client {

  type Character
  object Character {

    final case class CharacterView[FriendsSelection](name: String, age: Int, friends: List[FriendsSelection])

    type ViewSelection[FriendsSelection] = SelectionBuilder[Character, CharacterView[FriendsSelection]]

    def view[FriendsSelection](friendsFilter: Option[String] = None)(
      friendsSelection: SelectionBuilder[Character, FriendsSelection]
    ): ViewSelection[FriendsSelection] = (name ~ age ~ friends(friendsFilter)(friendsSelection)).map {
      case ((name, age), friends) => CharacterView(name, age, friends)
    }

    def name: SelectionBuilder[Character, String] = Field("name", Scalar())
    def age: SelectionBuilder[Character, Int]     = Field("age", Scalar())
    def friends[A](
      filter: Option[String] = None
    )(innerSelection: SelectionBuilder[Character, A]): SelectionBuilder[Character, List[A]] =
      Field("friends", ListOf(Obj(innerSelection)), arguments = List(Argument("filter", filter)))
  }
}
```


## Partial results

Yes, it will fetch all available fields. For partial results, you should define a custom schema.


The reason behind this change is to preserve the consistency between text schema and generated models.

When you add a new field to the schema, you can simply forget to propagate it to the models in tests. When the view is generated from the text schema, the chance to forget a new field is lower.

**Comment by ghostdogpr** [comment]
(sorry for my lack of feedback, very busy at work, I should have more time to look at it next weekend, or at last the week after that 🙏 )

**Review by ghostdogpr — COMMENTED** [review]
This is a great idea!

Can you also expose the option in the sbt plugin?
Also would be nice to mention it in the docs with an example.

**Comment by ghostdogpr** [comment]
Also, some conflicts appeared, can you rebase to the latest master?

**Comment by iRevive** [comment]
@ghostdogpr done. I'm curious, why CircleCI does not run tests for my branch?

**Comment by ghostdogpr** [comment]
Right, this is weird. It happened in the past, logging out and relogin to github and/or circleCI solved it (not sure which one actually matters).

**Comment by iRevive** [comment]
@ghostdogpr relogin to circleCI helped, thank you

**Review by paulpdaniels — APPROVED** [review]
I was about to ask to include a flag for turning it on but I see you were already a step ahead of me.

**Comment by iRevive** [comment]
Let me update the formatting of the generated code and the tests should be green

**Comment by iRevive** [comment]
@ghostdogpr the build is green. Could you review the PR again, please?

**Comment by ghostdogpr** [comment]
> This is a great idea!
> 
> Can you also expose the option in the sbt plugin?
> Also would be nice to mention it in the docs with an example.

@iRevive how about that?

**Comment by iRevive** [comment]
> > This is a great idea!
> 
> > 
> 
> > Can you also expose the option in the sbt plugin?
> 
> > Also would be nice to mention it in the docs with an example.
> 
> 
> 
> @iRevive how about that?

Sounds good. Will do so tomorrow

**Review by ghostdogpr — APPROVED** [review]
Very nice test suite! Thanks a lot.

**Pull request merged**
