### PR TITLE
update tapir to 1.0.1

### PR DESCRIPTION
**Pull request by rolang**
Hello,
it would be great if the library was compatible with the recent tapir `1.0.*` release and ZIO 1, as I needed it :). I noticed that it didn't require so many changes, so here is a small PR which I hope is helpful.
Cheers!

### CODE REVIEW

**Comment by rolang** [comment]
Looks like I missed some things, will have a look at the CI errors

**Comment by ghostdogpr** [comment]
Yeah looks like it's just the examples project.

**Comment by rolang** [comment]
> Yeah looks like it's just the examples project.

Right, ok CI looks good now.

**Review by ghostdogpr — APPROVED** [review]
Thanks!

**Pull request merged**
