### PR TITLE
Generator improvements

### PR DESCRIPTION
**Pull request by nikodemin**
* refactor generators code and tests
* make possible to generate graphQL interface in schema generator
* delete redundant implicits package
* add GenType argument for plugin to make convenient schema generation

### CODE REVIEW

**Comment by nikodemin** [comment]
@ghostdogpr Hi! I made several improvements in schema generator. Could you please check this pr, when you will have some free time?

**Comment by ghostdogpr** [comment]
Thanks! It's a little bit hard to review because things moved around and the github diff shows as if everything changed. I'll need to spend more time to check it out.

I just merged a change of the list of reserved keywords, can you rebase and include it into your PR?

**Review by ghostdogpr — APPROVED** [review]

**Comment by nikodemin** [comment]
@ghostdogpr Hi! Thank you for review, I merged changes from master branch

**Review by ghostdogpr — APPROVED** [review]
Thanks!

**Comment by kubukoz** [comment]
If only I'd seen this a week ago, I would've saved so much time :joy:

Thanks a lot @nikodemin :pray: I really needed a way to generate server schemas.

**Pull request merged**
