### PR TITLE
WIP: update zio to 2.0.0, zio-http to SNAPSHOT

### PR DESCRIPTION
**Pull request by aleksandr-vin**
Update zio -> 2.0.0

zio-http is a SNAPSHOT for now

### CODE REVIEW

**Comment by aleksandr-vin** [comment]
Waiting for https://github.com/softwaremill/sttp/pull/1469

**Comment by aleksandr-vin** [comment]
Waiting for https://github.com/dream11/zio-http/issues/1348

**Comment by ghostdogpr** [comment]
Thanks for preparing this! Once zio-http is released we will need a tapir release as well. The other missing bit I can see is the cats interop for cats effect 2.x (sadly still needed for monix interop).

**Comment by aleksandr-vin** [comment]
Waiting for https://github.com/softwaremill/tapir/pull/2263

**Comment by ghostdogpr** [comment]
Okay both zio-http and sttp were released, we're getting closer 😄

**Comment by ghostdogpr** [comment]
cats-interop also released, I think we're only missing tapir now

**Comment by ngbinh** [comment]
tapir 1.0.2 has been released with zio 2.0 https://github.com/softwaremill/tapir/releases/tag/v1.0.2

**Comment by ghostdogpr** [comment]
Merging and I will finish

**Pull request merged**
