### PR TITLE
Migrate to ZIO 2.0

### LINKED ISSUE #1041: Migrate to ZIO 2.0
We should start adding a 2.0 branch once the ZIO 2.0 API stabilizes a bit more (and there is some more support across other libraries).

TODO:
- [x] zio-query
- [x] zio-config
- [x] zio-json
- [x] zio-http
- [x] sttp (async-http-client-backend-zio)
- [x] tapir
- [x] zio-interop-cats
- [x] zio-interop-reactivestreams

### PR DESCRIPTION
**Pull request by ghostdogpr**
Closes #1041

- [x] core
- [x] client
- [x] clientLaminext
- [x] tools
- [x] codegenSbt
- [x] catsInterop
- [x] monixInterop
- [x] tapirInterop
- [x] http4s
- [x] zioHttp
- [x] akkaHttp
- [x] play
- [x] examples
- [x] benchmarks
- [x] federation

### CODE REVIEW

**Comment by ghostdogpr** [comment]
Updated interop-cats. The next blocker is Tapir.

**Comment by ghostdogpr** [comment]
Migrated `tools` and `codegenSbt`

**Comment by ghostdogpr** [comment]
Opened https://github.com/softwaremill/tapir/pull/1807 to add support for both ZIO 1.0 and 2.0 to Tapir

**Comment by ghostdogpr** [comment]
Migrated adapters, examples and zio-json. Still waiting for tapir, which explains remaining failures.

**Comment by ghostdogpr** [comment]
Disabled reporting tests since they are failing/hanging cc @paulpdaniels

**Comment by aleksandr-vin** [comment]
Please check #1407

**Comment by aleksandr-vin** [comment]
Following this PR from Wadden Sea, at 4:11 AM :)

**Comment by ghostdogpr** [comment]
You can use `2.0.0-RC2+89-ff2d3a19-SNAPSHOT` already =)

I will do the release later, I want to release a last 1.x first.

**Pull request closed without merging**
