### PR TITLE
#420. add routing (application/graphql) in finch.

### PR DESCRIPTION
**Pull request by keyno63**
Implement routing POST request in the case of finch. for #420.
This PR is my first challenge for function of caliban, please tell me bad point.

### CODE REVIEW

**Comment by ghostdogpr** [comment]
Oh, I didn't notice before I merged but the CI didn't run, not sure why 🤔  I will fix the linting issue on master.

**Comment by keyno63** [comment]
Thank you, approve.
And Sorry I missed to check format.
I will study scalafmtCheck.

**Comment by ghostdogpr** [comment]
It's not your fault, normally the CI is supposed to run when you open a PR but it didn't work 🤔 To format the code you can simply run `fmt` in sbt.

**Comment by keyno63** [comment]
Thanks a lot, I understand to use scala fmt.
and thank to fix code :bow:

**Pull request merged**
