### PR TITLE
Update tapir to 1.2.0

### PR DESCRIPTION
**Pull request by kyri-petrou**
Can't seem to replicate the error in CI from #1484 locally. Might have been a transient issue?

### CODE REVIEW

**Comment by ghostdogpr** [comment]
How about tapir 1.2.0 ?

**Comment by ghostdogpr** [comment]
But yeah the scripted test seems flaky :'(

**Comment by kyri-petrou** [comment]
> How about tapir 1.2.0 ?

Tested a couple test suites locally and seems to work without any code changes. Updated the PR, let's hope CI agrees too 😅

**Comment by guizmaii** [comment]
Can we update it in `series/1.x` too maybe, please?

**Pull request merged**
