### PR TITLE
Remove blaze dependency from http4s module

### PR DESCRIPTION
**Pull request by kubukoz**

### CODE REVIEW

**Comment by ghostdogpr** [comment]
Good point! Oddly the CI is not triggered, can you try login to https://app.circleci.com/ ?

**Comment by kubukoz** [comment]
Done, I'll  push an empty commit and hope it runs something...

**Comment by ghostdogpr** [comment]
Yep, it worked!

**Comment by kubukoz** [comment]
got it, bringing it back for tests only :D

**Pull request merged**
