### PR TITLE
Fix Akka HTTP example

### PR DESCRIPTION
**Pull request by ghostdogpr**
The interpreter (and the service) were recreated at every API call.

### CODE REVIEW

**Comment by ghostdogpr** [comment]
@loicdescotte I'm wondering if we should keep `makeHttpServiceM`, since it is quite dangerous.
Because it creates the interpreter with `unsafeRun` , it should not be used inside `path { ... }` otherwise the interpreter is recreated every time. It works if you call `makeHttpServiceM` outside of `path { ... }` and store the route in a val like I did in this PR, but still I find it dangerous. What do you think?

**Comment by loicdescotte** [comment]
If I understand correctly, it's more an issue with the little refactoring I've done rather than an issue with `makeHttpServiceM`, because in the first steps of my refactoring there was the same problem without `makeHttpServiceM` : 

```scala
val route =
    path("api" / "graphql") {
      runtime.unsafeRun(AkkaHttpAdapter.makeHttpService(interpreter))
    } ~ path("graphiql") {
      getFromResource("graphiql.html")
    }
```

This this code we would have the same issue, right?

**Comment by ghostdogpr** [comment]
Yeah we would have the same issue, but at least it's obvious that you create the interpreter every time.

With `makeHttpServiceM` we're hiding the fact that we're doing the `unsafeRun`. We're just returning the `Route` so library users will definitely put it directly under `path` and have the issue, no?

**Comment by loicdescotte** [comment]
I liked the fact that we could let the framework do the "dirty" unsafe job and let the user write an app in a pure way, but I understand your point and I don't see another way to do it so, yes maybe it needs to be removed :)

**Comment by ghostdogpr** [comment]
@loicdescotte to emphasize it's not the interpreter that needs an effect, I put the `unsafeRun` around `ExampleService.make(sampleCharacters)`.

**Pull request merged**
